services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - facade
    develop:
      watch:
        - action: sync+restart
          path: ./nginx.conf
          target: /etc/nginx/conf.d/default.conf

  facade:
    build:
      context: .
      dockerfile: ./facade.Dockerfile
    depends_on:
      - instance1
      - instance2
      - instance3
      - instance4
      - instance5
      - instance6
      - instance7
      - instance8
      - instance9
    develop:
      watch:
        - action: sync+restart
          path: ./facade.mjs
          target: /server/facade.mjs

  instance1: &instance-base
    build:
      context: .
      dockerfile: ./instance.Dockerfile
    develop:
      watch:
        - action: sync+restart
          path: ./instance.mjs
          target: /server/instance.mjs
    ports:
      - "58881:58080"

  instance2:
    <<: *instance-base
    ports:
      - "58882:58080"

  instance3:
    <<: *instance-base
    ports:
      - "58883:58080"

  instance4:
    <<: *instance-base
    ports:
      - "58884:58080"

  instance5:
    <<: *instance-base
    ports:
      - "58885:58080"

  instance6:
    <<: *instance-base
    ports:
      - "58886:58080"

  instance7:
    <<: *instance-base
    ports:
      - "58887:58080"

  instance8:
    <<: *instance-base
    ports:
      - "58888:58080"

  instance9:
    <<: *instance-base
    ports:
      - "58889:58080"
