services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"

  instance-base: &instance-base
    image: node:22-alpine
    working_dir: /server
    command: node instance.mjs
    volumes:
      - .:/server

  instance1:
    <<: *instance-base
    ports:
      - "58080:58080"

  instance2:
    <<: *instance-base

  instance3:
    <<: *instance-base

  instance4:
    <<: *instance-base

  instance5:
    <<: *instance-base

  instance6:
    <<: *instance-base

  instance7:
    <<: *instance-base

  instance8:
    <<: *instance-base

  instance9:
    <<: *instance-base
