services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - instance1
      - instance2
      - instance3
      - instance4
      - instance5
      - instance6
      - instance7
      - instance8
      - instance9
    develop:
      watch:
        - action: sync+restart
          path: ./nginx.conf
          target: /etc/nginx/conf.d/default.conf

  instance-base: &instance-base
    build:
      context: .
      dockerfile: ./node.Dockerfile
    develop:
      watch:
        - action: sync+restart
          path: ./instance.mjs
          target: /server/instance.mjs

  instance1:
    <<: *instance-base
    ports:
      - "58080:58080"

  instance2:
    <<: *instance-base

  instance3:
    <<: *instance-base

  instance4:
    <<: *instance-base

  instance5:
    <<: *instance-base

  instance6:
    <<: *instance-base

  instance7:
    <<: *instance-base

  instance8:
    <<: *instance-base

  instance9:
    <<: *instance-base
